### ISSUE TITLE
Generation of shares

### ISSUE THREAD

**Issue by ruimarinho** [trezor/python-shamir-mnemonic#1]
Hi,

The spec mentions:

> This construction yields a beneficial property where the identifier transforms into exactly the first three words of the mnemonic code, so the user can immediately tell whether the correct shares are being combined (i.e. they have to have the same first three words). Moreover, the forth word encodes exactly the index/threshold values, so for example share #2 of 3 required shares will always correspond to the same word.

However, I don't observe this when generating the shares. Could you provide some additional clarification?

**Comment by prusnak** [comment]
The specification of SLIP-0039 is subject to change. Do not use any implementation for now.
