### ISSUE TITLE
verbose -p cli options not recognized by --help

### ISSUE THREAD

**Issue by MrMebelMan** [trezor/python-shamir-mnemonic#10]
A little nitpick, [password_prompt](https://github.com/trezor/python-shamir-mnemonic/blob/master/shamir_mnemonic/cli.py#L41) and [passphrase_prompt](https://github.com/trezor/python-shamir-mnemonic/blob/master/shamir_mnemonic/cli.py#L150)  arguments lack the `--` prefix, so they are not recognized by `--help` correctly.

P.S.: maybe it's a good idea to use capital "P" for the `--password` option?

**Comment by matejcik** [comment]
they're not recognized by the command either, the verbose options don't exist ;)
