### ISSUE TITLE
Test Vector metadata

### ISSUE THREAD

**Issue by yeastplume** [trezor/python-shamir-mnemonic#11]
It might make life a bit easier for implementation authors if the test vector data included some metadata denoting why the test should fail. For instance, testing the third vector failed for me, but it took some digging to determine that the point of that particular mnemonic was to test a case where the padding bits aren't all zero.

**Comment by yeastplume** [comment]
Right, sorry I see it's in the python generation script now. Might be useful to have them spit out into the json somehow, but no big deal if not.

**Comment by andrewkozlik** [comment]
Good point. Done. https://github.com/trezor/python-shamir-mnemonic/commit/0f504b0f82a3e5e30c567cb073061d913b6c415d

**Comment by yeastplume** [comment]
:+1:
