### ISSUE TITLE
Alignment with spec and other reference implementations

### ISSUE THREAD

**Issue by ruimarinho** [trezor/python-shamir-mnemonic#2]
Hi,

I've been testing a couple of reference implementations and it looks like [jakubtrnka/ShamirsSecretSharingScheme](https://github.com/jakubtrnka/ShamirsSecretSharingScheme) is not producing compatible shares. Is this tool more aligned with the spec at this point?

Thanks!

**Comment by prusnak** [comment]
The specification of SLIP-0039 is subject to change. Do not use any implementation for now.
