### ISSUE TITLE
release shamir-mnemonic 0.2.0

### ISSUE THREAD

**Issue by matejcik** [trezor/python-shamir-mnemonic#28]
#27 has changed the internal APIs significantly, and despite the external APIs being identical, it would still be useful to publish the result.

However, I don't want to do that immediately. I would leave this in the repository for a couple of weeks to gather possible feedback, and only release version 0.2.0 in early 2020

**Comment by jonathancross** [comment]
Seems that v0.2.0 should be released. :-)

**Comment by matejcik** [comment]
fixed :)
