### ISSUE TITLE
Feature request: Permit other kinds of strings as input?

### ISSUE THREAD

**Issue by kristovatlas** [trezor/python-shamir-mnemonic#36]
Is there any appetite to add the ability to accept a BIP39 passphrase as input?

A simple way to implement this would be to convert the phrase into a canonical hex representation and then pass that in as the master-secret.

One simple and relatively compact way to compress a BIP39 passphrase down is to treat each word as a three-digit hex value between 000 and 7ff, as there are 2048 words in the BIP39 wordlist.

If there's interest, I would be happy to submit a PR.

**Comment by prusnak** [comment]
BIP-39 is intentionally not supported - read https://github.com/satoshilabs/slips/blob/master/slip-0039.md#design-rationale point 9

**Comment by kristovatlas** [comment]
Should have finished RTFM. Thanks for the explanation.
