### ISSUE TITLE
Master secret can't be used to create a compatible mnemonic seed

### ISSUE THREAD

**Issue by noamha** [trezor/python-shamir-mnemonic#37]
1. I used my Trezor to create a 2 out of 3 Shamir, here are 2 of parts:
```
admit upstairs academic acid disease frequent medal rich domain receiver fragment extra maiden airline triumph airline hormone lips research briefing
admit upstairs academic agency crunch provide spew overall voice exotic smell umbrella dining climate activity club editor item hesitate mustang
```
2 I used the `shamir recover` to acquire the master secret, which resulted in the following master secret
```
0db59247dfa48d61e5809337423e5371
```
3. I used various services including https://github.com/trezor/python-mnemonic, with this code:
```
from mnemonic import Mnemonic
mnemo = Mnemonic("english")

data = bytes.fromhex("0db59247dfa48d61e5809337423e5371")
mnemo.to_mnemonic(data)
```
4. Which resulted in this mnemonic seed
```
asset prosper music satisfy emotion rail noodle bar dance ball network tiny
```

When restoring the Trezor with the seed list it doesn't result in the same wallet. There's a chance I'm using the master secret incorrectly, in which case I would appreciate if you could guide me.

Thanks,
Noam.

**Comment by prusnak** [comment]
You can't convert shamir mnemonics to mnemonics and vice versa.

See https://github.com/satoshilabs/slips/blob/master/slip-0039.md#Bip39Compatibility for rationale
