### ISSUE TITLE
Relax click constraint

### ISSUE THREAD

**Issue by mweinelt** [trezor/python-shamir-mnemonic#38]
The CLI works pretty well with click 8.0 from my testing, please consider relax the constraint on the dependency and making a new release.

**Comment by hegjon** [comment]
Would help with the official Fedora package, since click 8 will be shipped with Fedora 35.

https://src.fedoraproject.org/rpms/python-click
https://bugzilla.redhat.com/show_bug.cgi?id=1977511

**Comment by prusnak** [comment]
@matejcik can you please cut a release with click dependency relaxed?

**Comment by matejcik** [comment]
reopening until the good version is released

**Comment by matejcik** [comment]
shamir 0.2.2 was released
