### ISSUE TITLE
Where to find documentation for how to drive private key from the master secret?

### ISSUE THREAD

**Issue by Ahmed-Ali** [trezor/python-shamir-mnemonic#39]
Hi,
When I use the shamir tool in this repo to recover a master secret.
I wonder what other tools I will need to use in order to drive the wallet private key from this secret (with/without passphrase).

Any pointers are highly appreciated.

Thank you!

**Comment by prusnak** [comment]
https://github.com/satoshilabs/slips/blob/master/slip-0039.md

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
