### ISSUE TITLE
Q: About `extendable` validation

### ISSUE THREAD

**Issue by lontivero** [trezor/python-shamir-mnemonic#50]
During recovery, it is okay to assume all shares have the same value for `extendable` or should the code to verify that?

**Comment by andrewkozlik** [comment]
All shares must have the same value of the `extendable` flag and the code should verify that to be compliant with the specification and the reference implementation.

The SLIP 39 specification states in section [Combining the shares](https://github.com/satoshilabs/slips/blob/master/slip-0039.md#combining-the-shares)
> 1. Check the following conditions:
>     ...
>     - All shares MUST have the same identifier _id_, extendable backup flag _ext_, iteration exponent _e_, group threshold _GT_, group count _G_ and length.

Indeed this reference implementation checks that in `add_share()`:
https://github.com/trezor/python-shamir-mnemonic/blob/17fcce14736afe498871d3018e4fa9330443471a/shamir_mnemonic/recovery.py#L73-L76
where `matches()` checks that the common parameters are identical with the current set that is being recovered, including the extendable backup flag:
https://github.com/trezor/python-shamir-mnemonic/blob/17fcce14736afe498871d3018e4fa9330443471a/shamir_mnemonic/share.py#L41-L48

**Comment by lontivero** [comment]
Thank you, I didn't see it.
