### ISSUE TITLE
Print master secret on 'create'

### ISSUE THREAD

**Issue by slush0** [trezor/python-shamir-mnemonic#6]
After calling `shamir create 2of3`, master secret is not printed out to the console. It would be useful for checking that recovery produced the same secret.

**Comment by matejcik** [comment]
you can explicitly choose your master secret with the `-S` option
i'll add an option to print the generated one as well

**Comment by slush0** [comment]
Is there a need for yet another option? What's wrong on printing out the secret directly? Considering that you already have to use it on trusted computer if you really want to use that secret, and shares are printed on the display automatically. I would rather to keep stuff simple than adding options.

**Comment by matejcik** [comment]
eh, you're right, i'm doing it unconditionally now
